### PR TITLE
Small cookies fix in README.md

### PR DESCRIPTION
**Pull request by gordonbondon**

### CODE REVIEW

**Comment by esergion** [comment]
It actually looks like a typo [here](https://github.com/route/ferrum/blob/1a329f475d09c47e72c6da340670b1ab398be7ab/lib/ferrum/cookies.rb#L35) @route

**Comment by gordonbondon** [comment]
I guess it should be camelcase, same as a parameter for [`Network.setCookie`](https://vanilla.aslushnikov.com/?Network.setCookie). Lowercase `httponly` actually did not work for me, hence this PR 😄

**Comment by route** [comment]
I had similar discussion regarding screenshot and pdf options. Everywhere in the gem I intended to use ruby style and underscored options, so it should have been httponly, but I don't recall regarding this one. I think the key is `Network.getCookies` rather than `Network.setCookie` so I think it's a bug rather than a typo.

**Comment by esergion** [comment]
Yea :), but camelcase-symbol is not usual for "ruby world", in fact it's described in many different style guides. So I'm a little hesitant, maybe we should translate it to lowercase in ferrum/cuprite

**Comment by gordonbondon** [comment]
Both `Network.getCookies` and `Network.setCookie` are valid. I guess I can replace  this doc update with a PR to ferrum like this?

**Comment by route** [comment]
@gordonbondon sounds good

**Pull request closed without merging**
